// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  tilSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Daily',
      link: {
        type: 'generated-index',
        title: '날짜별 학습 일지',
        description: 'OS, Network, 정보처리기사 공부 내용을 날짜별로 기록합니다.',
      },
      items: [{type: 'autogenerated', dirName: 'daily'}],
    },
  ],
};

export default sidebars;
